version: '3.7'

services:
    client:
        container_name: client
        build:
            context: ./client
            dockerfile: Dockerfile
        volumes:
            - './client:/usr/src/app/client'
            - '/app/client/node_modules'
        ports:
            - 3000:3000
        environment:
            - NODE_ENV=development
        restart: on-failure

    soundfy-api:
        container_name: soundfy-api
        image: soundfy-api
        build: 
            context: ./api
            dockerfile: Dockerfile
        networks:
            - api-network
        ports:
            - "5000:5000"
        volumes:
            - ./api/:/usr/src/app/api
            - /app/node_modules/
            
    mongo-media:
        container_name: mongo-media
        image: mongo:latest
        networks: 
            - media-network
        volumes:
            - ./mongo-database:/data/db
            
networks:
    api-network:
        driver: bridge
   