version: '3.7'

services:
    client:
        container_name: client
        build:
            context: ./client
            dockerfile: Dockerfile.prod
        ports:
            - 80:80
        environment:
            - NODE_ENV=production
        restart: on-failure

    user-service:
        container_name: user-service
        image: user-service
        build: 
            context: ./users
            dockerfile: Dockerfile
        networks:
            - user-network
        ports:
            - "5000:5000"
        volumes:
            - ./users/:/usr/src/app/users
            - /app/node_modules/

    media-service:
        container_name: media-service
        image: media-service
        build: 
            context: ./media
            dockerfile: Dockerfile
        networks:
            - media-network
        ports:
            - "5001:5000"
        volumes:
            - ./media/:/usr/src/app/media
            - /app/node_modules/

    mongo-media:
        container_name: mongo-media
        image: mongo:latest
        networks: 
            - media-network
        volumes:
            - ./mongo-database:/data/db
            
networks:
    user-network:
        driver: bridge
    media-network:
        driver: bridge